# Generated by Django 6.0.3 on 2026-04-21 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='notes.notes'),
        ),
    ]
